version: '3.9'
services:
  pencil:
    container_name: Pencil
    pull_policy: build
    build: https://github.com/BrackeysBot/Pencil.git#main
    volumes:
      - type: bind
        source: /var/log/brackeysbot/pencil
        target: /app/logs
      - type: bind
        source: /etc/brackeysbot/pencil
        target: /app/data
    restart: always
    environment:
      - DISCORD_TOKEN=${DISCORD_TOKEN}
